### ISSUE TITLE
java.util.NoSuchElementException: List is empty. on opening a kotlin file

### ISSUE THREAD

**Issue by mschaaf** [bvfalcon/kotlin-eclipse-2023#34]
> java.util.NoSuchElementException: List is empty.
> 	at kotlin.collections.CollectionsKt___CollectionsKt.single(_Collections.kt:608)
> 	at org.jetbrains.kotlin.core.resolve.BuiltInsReferenceResolver.initialize(BuiltInsReferenceResolver.java:120)
> 	at org.jetbrains.kotlin.core.resolve.BuiltInsReferenceResolver.<init>(BuiltInsReferenceResolver.java:75)
> 	at org.jetbrains.kotlin.core.model.KotlinCommonEnvironment.<init>(KotlinCommonEnvironment.kt:153)
> 	at org.jetbrains.kotlin.core.model.KotlinEnvironment.<init>(KotlinEnvironment.kt:322)
> 	at org.jetbrains.kotlin.core.model.KotlinEnvironment.<init>(KotlinEnvironment.kt)
> 	at org.jetbrains.kotlin.core.model.KotlinEnvironment$Companion$environmentCreation$1.invoke(KotlinEnvironment.kt:403)
> 	at org.jetbrains.kotlin.core.model.KotlinEnvironment$Companion$environmentCreation$1.invoke(KotlinEnvironment.kt:402)
> 	at org.jetbrains.kotlin.core.model.CachedEnvironment.getOrCreateEnvironment(CachedEnvironment.kt:37)
> 	at org.jetbrains.kotlin.core.model.KotlinEnvironment$Companion.getEnvironment(KotlinEnvironment.kt:408)
> 	at org.jetbrains.kotlin.core.model.KotlinEnvironmentKt.getEnvironment(KotlinEnvironment.kt:90)
> 	at org.jetbrains.kotlin.ui.editors.highlighting.KotlinTokenScanner.createKtFile(KotlinTokenScanner.java:104)
> 	at org.jetbrains.kotlin.ui.editors.highlighting.KotlinTokenScanner.setRange(KotlinTokenScanner.java:62)
> 	at org.eclipse.jface.text.rules.DefaultDamagerRepairer.createPresentation(DefaultDamagerRepairer.java:176)
> 	at org.eclipse.jface.text.presentation.PresentationReconciler.createPresentation(PresentationReconciler.java:436)
> 	at org.eclipse.jface.text.presentation.PresentationReconciler.processDamage(PresentationReconciler.java:549)
> 	at org.eclipse.jface.text.presentation.PresentationReconciler$InternalListener.inputDocumentChanged(PresentationReconciler.java:121)
> 	at org.eclipse.jface.text.TextViewer.fireInputDocumentChanged(TextViewer.java:2849)
> 	at org.eclipse.jface.text.TextViewer.setDocument(TextViewer.java:2890)
> 	at org.eclipse.jface.text.source.SourceViewer.setDocument(SourceViewer.java:682)
> 	at org.eclipse.jface.text.source.projection.ProjectionViewer.setDocument(ProjectionViewer.java:368)
> 	at org.eclipse.jface.text.source.SourceViewer.setDocument(SourceViewer.java:632)
> 	at org.eclipse.ui.texteditor.AbstractTextEditor.initializeSourceViewer(AbstractTextEditor.java:3980)
> 	at org.eclipse.ui.texteditor.AbstractTextEditor.createPartControl(AbstractTextEditor.java:3472)
> 	at org.eclipse.ui.texteditor.StatusTextEditor.createPartControl(StatusTextEditor.java:64)
> 	at org.eclipse.ui.texteditor.AbstractDecoratedTextEditor.createPartControl(AbstractDecoratedTextEditor.java:454)
> 	at org.eclipse.jdt.internal.ui.javaeditor.JavaEditor.createPartControl(JavaEditor.java:3093)
> 	at org.eclipse.jdt.internal.ui.javaeditor.CompilationUnitEditor.createPartControl(CompilationUnitEditor.java:1522)
> 	at org.jetbrains.kotlin.ui.editors.KotlinCommonEditor.createPartControl(KotlinCommonEditor.kt:95)
> 	at org.eclipse.ui.internal.e4.compatibility.CompatibilityPart.createPartControl(CompatibilityPart.java:158)
> 	at org.eclipse.ui.internal.e4.compatibility.CompatibilityEditor.createPartControl(CompatibilityEditor.java:96)
> 	at org.eclipse.ui.internal.e4.compatibility.CompatibilityPart.create(CompatibilityPart.java:365)
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
> 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
> 	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:58)
> 	at org.eclipse.e4.core.internal.di.InjectorImpl.processAnnotated(InjectorImpl.java:995)
> 	at org.eclipse.e4.core.internal.di.InjectorImpl.processAnnotated(InjectorImpl.java:960)
> 	at org.eclipse.e4.core.internal.di.InjectorImpl.internalInject(InjectorImpl.java:140)
> 	at org.eclipse.e4.core.internal.di.InjectorImpl.internalMake(InjectorImpl.java:403)
> 	at org.eclipse.e4.core.internal.di.InjectorImpl.make(InjectorImpl.java:330)
> 	at org.eclipse.e4.core.contexts.ContextInjectionFactory.make(ContextInjectionFactory.java:202)
> 	at org.eclipse.e4.ui.internal.workbench.ReflectionContributionFactory.createFromBundle(ReflectionContributionFactory.java:91)
> 	at org.eclipse.e4.ui.internal.workbench.ReflectionContributionFactory.doCreate(ReflectionContributionFactory.java:60)
> 	at org.eclipse.e4.ui.internal.workbench.ReflectionContributionFactory.create(ReflectionContributionFactory.java:42)
> 	at org.eclipse.e4.ui.workbench.renderers.swt.ContributedPartRenderer.createWidget(ContributedPartRenderer.java:132)
> 	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.createWidget(PartRenderingEngine.java:995)
> 	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.safeCreateGui(PartRenderingEngine.java:659)
> 	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.safeCreateGui(PartRenderingEngine.java:763)
> 	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$2.run(PartRenderingEngine.java:728)
> 	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
> 	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.createGui(PartRenderingEngine.java:712)
> 	at org.eclipse.e4.ui.internal.workbench.PartServiceImpl.lambda$0(PartServiceImpl.java:105)
> 	at org.eclipse.e4.ui.services.internal.events.UIEventHandler.lambda$0(UIEventHandler.java:38)
> 	at org.eclipse.swt.widgets.Synchronizer.syncExec(Synchronizer.java:183)
> 	at org.eclipse.ui.internal.UISynchronizer.syncExec(UISynchronizer.java:133)
> 	at org.eclipse.swt.widgets.Display.syncExec(Display.java:5960)
> 	at org.eclipse.e4.ui.workbench.swt.DisplayUISynchronize.syncExec(DisplayUISynchronize.java:34)
> 	at org.eclipse.e4.ui.services.internal.events.UIEventHandler.handleEvent(UIEventHandler.java:38)
> 	at org.eclipse.equinox.internal.event.EventHandlerWrapper.handleEvent(EventHandlerWrapper.java:205)
> 	at org.eclipse.equinox.internal.event.EventHandlerTracker.dispatchEvent(EventHandlerTracker.java:203)
> 	at org.eclipse.equinox.internal.event.EventHandlerTracker.dispatchEvent(EventHandlerTracker.java:1)
> 	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234)
> 	at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:151)
> 	at org.eclipse.equinox.internal.event.EventAdminImpl.dispatchEvent(EventAdminImpl.java:133)
> 	at org.eclipse.equinox.internal.event.EventAdminImpl.sendEvent(EventAdminImpl.java:75)
> 	at org.eclipse.equinox.internal.event.EventComponent.sendEvent(EventComponent.java:44)
> 	at org.eclipse.e4.ui.services.internal.events.EventBroker.send(EventBroker.java:55)
> 	at org.eclipse.e4.ui.internal.workbench.UIEventPublisher.notifyChanged(UIEventPublisher.java:63)
> 	at org.eclipse.emf.common.notify.impl.BasicNotifierImpl.eNotify(BasicNotifierImpl.java:424)
> 	at org.eclipse.e4.ui.model.application.ui.impl.ElementContainerImpl.setSelectedElementGen(ElementContainerImpl.java:170)
> 	at org.eclipse.e4.ui.model.application.ui.impl.ElementContainerImpl.setSelectedElement(ElementContainerImpl.java:188)
> 	at org.eclipse.e4.ui.internal.workbench.ModelServiceImpl.showElementInWindow(ModelServiceImpl.java:660)
> 	at org.eclipse.e4.ui.internal.workbench.ModelServiceImpl.bringToTop(ModelServiceImpl.java:624)
> 	at org.eclipse.e4.ui.internal.workbench.PartServiceImpl.delegateBringToTop(PartServiceImpl.java:790)
> 	at org.eclipse.e4.ui.internal.workbench.PartServiceImpl.bringToTop(PartServiceImpl.java:401)
> 	at org.eclipse.e4.ui.internal.workbench.PartServiceImpl.showPart(PartServiceImpl.java:1264)
> 	at org.eclipse.ui.internal.WorkbenchPage.busyOpenEditor(WorkbenchPage.java:3210)
> 	at org.eclipse.ui.internal.WorkbenchPage.lambda$9(WorkbenchPage.java:3100)
> 	at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:67)
> 	at org.eclipse.ui.internal.WorkbenchPage.openEditor(WorkbenchPage.java:3098)
> 	at org.eclipse.ui.internal.WorkbenchPage.openEditor(WorkbenchPage.java:3068)
> 	at org.eclipse.ui.internal.WorkbenchPage.openEditor(WorkbenchPage.java:3059)
> 	at org.eclipse.ui.ide.IDE.openEditor(IDE.java:548)
> 	at org.eclipse.ui.ide.IDE.openEditor(IDE.java:508)
> 	at org.eclipse.ui.internal.ide.handlers.OpenResourceHandler.execute(OpenResourceHandler.java:129)
> 	at org.eclipse.ui.internal.ide.handlers.OpenResourceHandler.run(OpenResourceHandler.java:182)
> 	at org.eclipse.ui.internal.handlers.ActionDelegateHandlerProxy.execute(ActionDelegateHandlerProxy.java:288)
> 	at org.eclipse.ui.internal.handlers.E4HandlerProxy.execute(E4HandlerProxy.java:97)
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
> 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
> 	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:58)
> 	at org.eclipse.e4.core.internal.di.InjectorImpl.invokeUsingClass(InjectorImpl.java:317)
> 	at org.eclipse.e4.core.internal.di.InjectorImpl.invoke(InjectorImpl.java:251)
> 	at org.eclipse.e4.core.contexts.ContextInjectionFactory.invoke(ContextInjectionFactory.java:173)
> 	at org.eclipse.e4.core.commands.internal.HandlerServiceHandler.execute(HandlerServiceHandler.java:156)
> 	at org.eclipse.core.commands.Command.executeWithChecks(Command.java:488)
> 	at org.eclipse.core.commands.ParameterizedCommand.executeWithChecks(ParameterizedCommand.java:485)
> 	at org.eclipse.e4.core.commands.internal.HandlerServiceImpl.executeHandler(HandlerServiceImpl.java:213)
> 	at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher.executeCommand(KeyBindingDispatcher.java:308)
> 	at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher.press(KeyBindingDispatcher.java:580)
> 	at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher.processKeyEvent(KeyBindingDispatcher.java:647)
> 	at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher.filterKeySequenceBindings(KeyBindingDispatcher.java:439)
> 	at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher$KeyDownFilter.handleEvent(KeyBindingDispatcher.java:96)
> 	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
> 	at org.eclipse.swt.widgets.Display.filterEvent(Display.java:1953)
> 	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1528)
> 	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1555)
> 	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1538)
> 	at org.eclipse.swt.widgets.Widget.sendKeyEvent(Widget.java:1577)
> 	at org.eclipse.swt.widgets.Widget.gtk_key_press_event(Widget.java:937)
> 	at org.eclipse.swt.widgets.Control.gtk_key_press_event(Control.java:4013)
> 	at org.eclipse.swt.widgets.Composite.gtk_key_press_event(Composite.java:931)
> 	at org.eclipse.swt.widgets.Tree.gtk_key_press_event(Tree.java:2372)
> 	at org.eclipse.swt.widgets.Widget.windowProc(Widget.java:2507)
> 	at org.eclipse.swt.widgets.Control.windowProc(Control.java:6834)
> 	at org.eclipse.swt.widgets.Tree.windowProc(Tree.java:4285)
> 	at org.eclipse.swt.widgets.Display.windowProc(Display.java:6163)
> 	at org.eclipse.swt.internal.gtk3.GTK3.gtk_main_do_event(Native Method)
> 	at org.eclipse.swt.widgets.Display.eventProc(Display.java:1597)
> 	at org.eclipse.swt.internal.gtk3.GTK3.gtk_main_iteration_do(Native Method)
> 	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4514)
> 	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1155)
> 	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
> 	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1046)
> 	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
> 	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:643)
> 	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
> 	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:550)
> 	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:171)
> 	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:152)
> 	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
> 	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
> 	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
> 	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:402)
> 	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
> 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
> 	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
> 	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
> 	at org.eclipse.equinox.launcher.Main.run(Main.java:1467)
> 	at org.eclipse.equinox.launcher.Main.main(Main.java:1440)
>

**Comment by lx-spb** [comment]
close all editor tabs in Eclipse, then uninstall all Kotlin software (Help -> About Eclipse IDE -> Installation Details)
reinstall Kotlin from Marketplace
that fixed it for me (Eclipse Version: 2023-06 4.28.0)
